package structs

import "github.com/jinzhu/gorm"

type CollegeTeamRecords struct {
	gorm.Model
	TeamID                       int
	PassingTDCareerHolderID      int
	PassingTDCareerHolder        string
	PassingTDCareerRecord        int
	PassingTDGameHolderID        int
	PassingTDGameHolder          string
	PassingTDGameRecord          int
	PassingTDSeasonHolderID      int
	PassingTDSeasonHolder        string
	PassingTDSeasonRecord        int
	PassingYardsCareerHolderID   int
	PassingYardsCareerHolder     string
	PassingYardsCareerRecord     int
	PassingYardsGameHolderID     int
	PassingYardsGameHolder       string
	PassingYardsGameRecord       int
	PassingYardsSeasonHolderID   int
	PassingYardsSeasonHolder     string
	PassingYardsSeasonRecord     int
	RushingTDCareerHolderID      int
	RushingTDCareerHolder        string
	RushingTDCareerRecord        int
	RushingTDGameHolderID        int
	RushingTDGameHolder          string
	RushingTDGameRecord          int
	RushingTDSeasonHolderID      int
	RushingTDSeasonHolder        string
	RushingTDSeasonRecord        int
	RushingYardsCareerHolderID   int
	RushingYardsCareerHolder     string
	RushingYardsCareerRecord     int
	RushingYardsGameHolderID     int
	RushingYardsGameHolder       string
	RushingYardsGameRecord       int
	RushingYardsSeasonHolderID   int
	RushingYardsSeasonHolder     string
	RushingYardsSeasonRecord     int
	ReceivingTDCareerHolderID    int
	ReceivingTDCareerHolder      string
	ReceivingTDCareerRecord      int
	ReceivingTDGameHolderID      int
	ReceivingTDGameHolder        string
	ReceivingTDGameRecord        int
	ReceivingTDSeasonHolderID    int
	ReceivingTDSeasonHolder      string
	ReceivingTDSeasonRecord      int
	ReceivingYardsCareerHolderID int
	ReceivingYardsCareerHolder   string
	ReceivingYardsCareerRecord   int
	ReceivingYardsGameHolderID   int
	ReceivingYardsGameHolder     string
	ReceivingYardsGameRecord     int
	ReceivingYardsSeasonHolderID int
	ReceivingYardsSeasonHolder   string
	ReceivingYardsSeasonRecord   int
	ReceptionsCareerHolderID     int
	ReceptionsCareerHolder       string
	ReceptionsCareerRecord       int
	ReceptionsGameHolderID       int
	ReceptionsGameHolder         string
	ReceptionsGameRecord         int
	ReceptionsSeasonHolderID     int
	ReceptionsSeasonHolder       string
	ReceptionsSeasonRecord       int
	InterceptionsCareerHolderID  int
	InterceptionsCareerHolder    string
	InterceptionsCareerRecord    int
	InterceptionsGameHolderID    int
	InterceptionsGameHolder      string
	InterceptionsGameRecord      int
	InterceptionsSeasonHolderID  int
	InterceptionsSeasonHolder    string
	InterceptionsSeasonRecord    int
	SacksCareerHolderID          int
	SacksCareerHolder            string
	SacksCareerRecord            int
	SacksGameHolderID            int
	SacksGameHolder              string
	SacksGameRecord              int
	SacksSeasonHolderID          int
	SacksSeasonHolder            string
	SacksSeasonRecord            int
	TacklesCareerHolderID        int
	TacklesCareerHolder          string
	TacklesCareerRecord          int
	TacklesGameHolderID          int
	TacklesGameHolder            string
	TacklesGameRecord            int
	TacklesSeasonHolderID        int
	TacklesSeasonHolder          string
	TacklesSeasonRecord          int
}
